"""add patients table

Revision ID: e94c2a272704
Revises: 402e69872805
Create Date: 2026-05-10 17:38:21.719072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94c2a272704'
down_revision: Union[str, Sequence[str], None] = '402e69872805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_medical_record_number_key'), 'patients', type_='unique')
    op.drop_column('patients', 'medical_record_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('medical_record_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('patients_medical_record_number_key'), 'patients', ['medical_record_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
